name: Sync latest build version to readme (filesize shield + GM import URL)

on:
  push:
    branches: [ master, main ]
    paths: 'dist/**'

jobs:
  build:
    if: contains(github.event.commits[0].message, 'buil')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chatgptjs/chatgpt.js
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: chatgptjs/chatgpt.js
          path: chatgptjs/chatgpt.js
          fetch-depth: 2

      - name: Find/replace latest version in READMEs
        env:
          COMMIT_MSG: ${{ github.event.commits[0].message }}
        run: |
          cd $GITHUB_WORKSPACE/chatgptjs/chatgpt.js/docs
          version=$(echo "$COMMIT_MSG" | grep -oE 'chatgpt-\d+\.\d+\.\d+\.min\.js' | head -1)
          version="${version//\`/}" # strip backticks
          sed -i "s/chatgpt-\d\+\.\d\+\.\d\+\.min\.js/$version/g" $(find . -name "README.md")

      - name: Find/replace latest commit hash in READMEs
        run: |
          cd $GITHUB_WORKSPACE/chatgptjs/chatgpt.js
          commit_hash=$(git rev-parse HEAD)
          sed -i "s/chatgpt.js@[a-f0-9]\+\//chatgpt.js@$commit_hash\//g" $(find docs -name "README.md")  # Use relative path for `find` command

      - name: Commit and push changes
        run: |
          cd $GITHUB_WORKSPACE/chatgptjs/chatgpt.js
          git config user.name "auto-sync-bot"
          git config user.email "auto-sync@chatgptjs.org"
          git add .
          git commit -m "Sync latest build version to README"
          git push
